/* Laura Capes Terry — blog content data (shared by blog.jsx + post.jsx).
   Plain JS, no JSX. Loaded before the babel page scripts.
   Each post: { slug, title, cat, date, sort, read, tags[], img, dek, body[] }
   body blocks: P(text) H(text) Q(text,cite) L([items]) — rendered by post.jsx. */
(function () {
  var P = function (t) { return { type: 'p', children: t }; };
  var H = function (t) { return { type: 'h2', children: t }; };
  var Q = function (t, c) { return { type: 'quote', children: t, cite: c }; };
  var L = function (items) { return { type: 'list', items: items }; };

  var slugify = function (s) {
    return String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60);
  };

  var posts = [
    {
      title: 'The Courage Was the Win',
      cat: 'Inspiration', date: 'Feb 16, 2026', sort: 20260216, read: '6 min read',
      tags: ['#Theunbridledcreative', '#Inspiration', '#Lauracapesterrymba'],
      img: 'blog/courage-was-the-win.jpg',
      dek: 'Last night, I live launched something I’d been sitting on for six years. But this isn’t really a story about a webinar — it’s a story about courage.',
      body: [
        P('Last night, I live launched something I’ve been sitting on for six years. But this isn’t really a story about a webinar. It’s a story about courage. About obedience. About becoming. And if you’re building something meaningful in your life or business, this is for you.'),
        H('The Thing I Built — and Hid'),
        P('In the spring of 2020, when the world shut down, I bought Amy Porterfield’s Digital Course Academy. I did the work. I built a course. I mapped the lessons, recorded the content, structured the modules. And then… I never live launched it.'),
        P('Why? Because building something quietly feels safe. Launching it publicly does not. For six years, that course sat quietly in the background — seen only by family and friends I gave it to for free. No big announcement. No bold invitation. No public step.'),
        P('If I’m honest, it wasn’t a strategy issue. It was a visibility issue. And maybe you understand that. Maybe you have:'),
        L(['An idea you haven’t released.', 'A program you haven’t offered.', 'A book you haven’t finished.', 'A calling you haven’t fully stepped into.']),
        P('Most of the time, it’s not about ability. It’s about courage.'),
        H('From Shy Farm Girl to Public Launch'),
        P('When I shared on the webinar that I grew up bone-chillingly shy on a farm in Illinois, I wasn’t exaggerating. Eye contact terrified me. Speaking terrified me. Being noticed terrified me.'),
        P('But every major shift in my life has followed the same pattern: I felt a nudge. I resisted. Then I stepped. Media sales. Leadership roles. Publishing. Writing books. Teaching workshops. Learning AI. None of it started with confidence. It started with obedience.'),
        Q('Confidence always followed the step — not the other way around. You don’t wait to feel ready. You grow ready by acting.', 'Laura Capes Terry, MBA'),
        H('Learning AI Was Another Stretch'),
        P('A few years ago, I felt that same internal pull again. Learn AI. Not because it was trendy — because I could see where business was going. So I did what I’ve always done: self-taught, trial and error, invested in courses, paid for certifications, and tested everything inside my own businesses.'),
        P('What I discovered surprised me. Most business owners aren’t afraid of AI. They’re afraid of losing their voice. They don’t want to sound generic. They don’t want to feel replaceable. They don’t want to build something hollow. That’s when the idea for “Teach ChatGPT How to Sound Like You” was born. Because AI isn’t the threat. Disconnection is.'),
        H('The Webinar Wasn’t the Win'),
        P('Yes, folks I care about deeply joined the AI Co-Pilot Cohort. Yes, that matters. But here’s the deeper truth: the win wasn’t revenue. The win was alignment.'),
        P('I did the thing I avoided for six years. I showed up publicly. I finished what I started. I honored the calling instead of shrinking from it. That changes you. When you act in alignment with who you’re becoming, something shifts internally. You trust yourself more. You think clearer. You lead differently. That’s the compound effect of courage.'),
        H('Leadership Is Not a Solo Sport'),
        P('There’s another part of this story that matters. I didn’t do this alone. My podcast co-host and dear friend, Trent Soles, ran the entire back end of the webinar. While I focused on teaching, he managed the Zoom room, engaged attendees in the chat, dropped links and resources, fielded questions, and protected the flow.'),
        P('We were in different states, but because of Zoom it felt like we were in the same room. And because of that partnership, I could stay fully in my role. That’s leadership — not doing everything, but knowing your role and letting others step into theirs.'),
        P('If you’re building something bigger, hear me clearly: you do not have to carry it alone. Growth eventually requires trust, delegation, collaboration, and shared vision. Teamwork doesn’t weaken leadership — it strengthens it. Because when vision is shared, impact multiplies.'),
        H('The Discipline of Becoming'),
        P('Becoming who you’re meant to be isn’t one giant leap. It’s disciplined, repeated steps. It’s showing up when it’s inconvenient, launching before you feel fully ready, investing before you see guaranteed return, choosing growth over comfort, and acting on nudges instead of silencing them.'),
        P('Six years ago, I built something and hid it. Last night, I built something and released it. That’s growth. And growth often feels vulnerable before it feels victorious.'),
        H('Why I Built the AI Co-Pilot Cohort'),
        P('This is exactly why I created the AI Co-Pilot Cohort — not just to teach prompts, but to help serious business owners clarify their messaging, strengthen their positioning, integrate AI without losing their voice, make faster and smarter decisions, market with confidence instead of confusion, and build leverage without sacrificing authenticity.'),
        P('Inside the cohort, I personally guide you through building your Voice Blueprint, creating your Master AI Co-Pilot Prompt, training ChatGPT to think with you (not replace you), and applying AI across your website, email, social, and offers. Three live sessions. Direct support. Real implementation. Clear direction. This isn’t about shortcuts. It’s about leadership in a changing world.'),
        H('The Invitation'),
        P('If you’ve been sensing that it’s time to step up… if you’ve been circling AI but unsure how to do it in a way that protects who you are… if you want clarity instead of chaos… this is your step. Not because it’s flashy. Because it’s aligned.'),
        P('If AI is your next stretch, I would be honored to walk with you. You don’t need to leap five years ahead. You just need to step.'),
        Q('The courage is the win. And becoming is always worth it.', 'Laura Capes Terry, MBA'),
      ],
    },
    {
      title: 'The Unbridled Creative Podcast launches this Tuesday!',
      cat: 'Podcast', date: 'Nov 09, 2025', sort: 20251109, read: '4 min read',
      tags: ['#Theunbridledcreative', '#Podcastepisode'],
      img: 'blog/unbridled-launch-tuesday.webp',
      dek: 'For months we’ve been praying, planning, and pouring our hearts into a space where faith, purpose, and entrepreneurship collide. That dream is now a reality.',
      body: [
        P('For months, we’ve been praying, planning, and pouring our hearts into something we believe the world needs right now — a space where faith, purpose, and entrepreneurship collide. That dream is now a reality. The Unbridled Creative Podcast launches this Tuesday!'),
        P('Hosted by Laura Capes Terry and Trent Soles, The Unbridled Creative is a new kind of business podcast — one where real stories of faith meet practical tools for growth. We’re two lifelong entrepreneurs who know what it means to dream big, walk through fear, and build something meaningful from the inside out. This podcast was born out of a desire to help others do the same.'),
        H('Each episode will bring you'),
        L([
          'Real God-stories — honest, unpolished conversations about courage, calling, and transformation.',
          'Practical takeaways — mindset and marketing insights to help you grow your business without losing your soul.',
          'Faith-based encouragement — reminders that you were created for more and that freedom begins when you stop holding back.',
        ]),
        P('Whether you’re starting something new, reinventing what’s next, or simply craving more meaning in your work, The Unbridled Creative will help you find the clarity, courage, and freedom to live unbridled.'),
        P('This has been a leap of faith — one we’ve taken because of the people who have believed in us from the very beginning. Your encouragement and prayers have meant everything as we’ve built this dream from the ground up. Now we can’t wait to invite you in.'),
        P('Listen and subscribe wherever you get your podcasts — follow on Spotify, subscribe on Apple Podcasts, and subscribe on YouTube. You can also bookmark theunbridledcreative.com for new releases, show notes, and behind-the-scenes updates.'),
        P('And if you love what you hear, we’d be honored if you shared our introductory episode with your community — on social media, in your newsletter, or wherever you connect with your people. Don’t forget to tag us @theunbridledcreative so we can celebrate alongside you.'),
        P('Thank you for believing in this movement and for walking with us as we step out in faith. With gratitude, Laura & Trent — Co-Hosts, The Unbridled Creative Podcast.'),
      ],
    },
    {
      title: 'Launching Soon: The Unbridled Creative Podcast',
      cat: 'Podcast', date: 'Oct 18, 2025', sort: 20251018, read: '3 min read',
      tags: ['#Theunbridledcreative', '#Podcastepisode'],
      img: 'blog/unbridled-riverside.png',
      dek: 'If you’ve been wondering what I’ve been up to behind the scenes… this is it.',
      body: [
        P('If you’ve been wondering what I’ve been up to behind the scenes… this is it.'),
        P('For months, Trent Soles and Laura Capes Terry have been quietly building something that’s been on our hearts for a long time — The Unbridled Creative Podcast.'),
        P('It started as a simple idea: to give courageous entrepreneurs a space to tell the stories of how they’ve chosen faith over fear and learned to live in alignment with their calling. What it’s become is so much more. It’s a movement. A message. And honestly, a labor of love.'),
        P('We’ve built a full brand from the ground up — colors, photography, website, intros, automation, and (my favorite part) the conversations. The kind that make you stop, think, and thank God for how He weaves purpose through every part of our journey.'),
        P('We’re getting close to launch now, and my prayer is that The Unbridled Creative will inspire you, equip you, and remind you that you were made for more. Because your story matters. And the world needs what God has placed inside you.'),
        Q('The Unbridled Creative — where courage meets calling.', 'Laura Capes Terry, MBA'),
        P('Join our email list to get notified when we launch: www.theunbridledcreative.com.'),
      ],
    },
    {
      title: 'Marketing Should Be the Lifeline of Your Business',
      cat: 'Strategy', date: 'Sep 24, 2025', sort: 20250924, read: '6 min read',
      tags: ['#Marketingmadesmarter', '#Lauracapesterrymba'],
      img: 'blog/marketing-lifeline.png',
      dek: 'When the world feels uncertain, fear becomes the worst marketing strategy. Here’s why the businesses that lean in are the ones that come out stronger.',
      body: [
        P('The world feels uncertain right now. Wars rage overseas. Tariffs rise. Inflation eats away at margins. Consumers hesitate, and some industries are seeing businesses close their doors. Fear is creeping into the marketplace — and with it, a temptation for business owners to shrink back.'),
        P('But here’s the truth: fear is the worst marketing strategy.'),
        P('I learned this the hard way. Back in 2007–2009, when the Great Recession rocked our economy, I watched 75% of the businesses in my industry at the time go under. They weren’t bad businesses. They weren’t run by bad people. They were simply unprepared, and when fear hit, they pulled back instead of leaning in.'),
        P('And yet, the ones who survived — and even came out stronger on the other side — were those who kept their marketing alive. They knew their marketing was not an expense to cut but the lifeline of their business.'),
        H('The Fishing Analogy'),
        P('Think about marketing like fishing. When fewer fish are biting, the instinct might be to pack up and go home. But if you leave, you’ve guaranteed that you won’t catch anything.'),
        P('The smarter move is to stay on the water — while also getting strategic. Maybe you try a new location. Maybe you change your bait. Maybe you go deeper. Maybe you adjust your timing. That’s the nuance of marketing, too. Leaning in doesn’t just mean spending more. It means adapting — refining your message, testing new channels, doubling down on what works, and having the courage to innovate while others retreat.'),
        P('And here’s the kicker: when other fishermen pack up their gear and walk away, your chances of catching a fish actually increase. The competition thins out, and the opportunities are still there for those willing to stay visible.'),
        H('Why Pulling Back Is Dangerous'),
        P('When business owners cut their marketing, they don’t just save money. They lose visibility. They lose mindshare. They lose momentum. And when the tide turns — as it always does — their competitors who stayed visible will be the ones standing strong, ready to capture the pent-up demand.'),
        H('Lean In, Get Smarter, Stay Strong'),
        P('Your marketing should be the lifeblood of your business. It’s not a magic pill. It’s not a lottery ticket. It’s a system — a process designed to help you attract, convert, and keep new customers. When times get tough, the most courageous and strategic thing you can do is double down on that system. Refine it. Strengthen it. Expand it. Because if your marketing isn’t serving as your lifeline right now, then it’s time to rework the strategy.'),
        H('My Invitation to You'),
        P('I’m encouraging my clients right now to lean into their marketing — not pull back. And I want to encourage you to do the same. If your current strategy feels like guesswork… if you’re not confident that your marketing is consistently attracting new customers… if you’re worried about weathering what’s ahead… let’s talk. Together, we can make your marketing the lifeline of your business — so that no matter what happens in the marketplace, you don’t just survive. You thrive.'),
        Q('Because when the fish stop biting, you don’t pack up and go home. You stay in the water, get smarter, and keep fishing.', 'Laura Capes Terry, MBA'),
      ],
    },
    {
      title: 'Inconsistent Posting Is Costing You More Than You Think',
      cat: 'Social Media', date: 'Aug 18, 2025', sort: 20250818, read: '5 min read',
      tags: ['#Marketingmadesmarter', '#socialmediamarketing', '#digitalmarketing'],
      img: 'blog/social-storefront.png',
      dek: 'Every business makes a first impression long before the phone rings — and today that first impression almost always happens on social media.',
      body: [
        P('Whether we realize it or not, every business makes a first impression — long before the phone rings, the email comes in, or someone walks through the door. And in today’s world, that first impression almost always happens on social media.'),
        H('Your Social Media Is Your Digital Front Porch'),
        P('Think of your social profile like your digital front porch. It’s where people go to peek in the windows, see if the lights are on, and decide: Do I trust this business? Do I like what I see? Do I want to step inside?'),
        P('This isn’t just a gut feeling — it’s backed by hard data. Research shows 81% of people check out a business on social media before ever engaging. They want to know: Are you trustworthy? Are you active? Do your values align with theirs?'),
        P('So if your social media is outdated, inconsistent, or all over the place, you don’t just look less professional — you instantly lose credibility. It’s like answering the door in your bathrobe with dishes in the sink and laundry on the couch. Nobody’s saying you’re not amazing at what you do. But that first impression? It’s not exactly outstanding.'),
        H('Most Business Owners Are Too Busy to Keep Up'),
        P('Now, I get it. You’re busy running your business. In fact, 64% of business owners say social media is taking time away from revenue-producing activities. So most either don’t post at all, or post without a plan. Both can cost you visibility and trust. And in a world where your next client is one click away from someone else, that matters.'),
        H('That’s Where Organic Social Reach Comes In'),
        P('That’s why I offer an essential service called Organic Social Reach. It’s a done-for-you, organic social media marketing solution that helps you show up online with consistency, clarity, and credibility. My team and I post on your behalf up to four times per week, every single week — so your online presence always feels alive, inviting, and on-brand.'),
        P('We don’t just check the “posting” box. We post with purpose: to build trust, to reflect your voice and values, and to make your business feel like one worth engaging with. Because your social media shouldn’t just look active. It should feel like you — professional, polished, and ready to serve.'),
        H('Want to Make a Better First Impression?'),
        P('If you know a business owner who is incredible in person but whose social media doesn’t do them justice, I’d love an introduction. Let’s make sure the moment someone checks you out online, you check all the boxes.'),
      ],
    },
    {
      title: 'Before you hire your next “marketing expert,” read this.',
      cat: 'Strategy', date: 'Aug 17, 2025', sort: 20250817, read: '7 min read',
      tags: ['#Marketingmadesmarter', '#Lauracapesterrymba'],
      img: 'blog/marketing-expert.png',
      dek: 'Not all “marketing experts” are created equal. Knowing one tactic doesn’t make someone a marketing expert — here’s what real marketing leadership requires.',
      body: [
        P('If you spend any time on LinkedIn, Instagram, or even in your local business community, you’ve probably noticed a growing number of people calling themselves “marketing experts.”'),
        P('Sometimes it’s because they’ve learned how to post on social media. Sometimes it’s because they’ve mastered a single tool or tactic, like Facebook ads or email automation. And sometimes it’s because they read the latest book from a well-known thought leader and began repeating the ideas as if they were their own.'),
        P('To be clear — there’s nothing wrong with learning new skills, trying new tools, or sharing what inspires you. Marketing is a field where we’re all constantly learning, and fresh perspectives matter. But here’s the truth most business owners don’t realize: knowing one tactic doesn’t make someone a marketing expert.'),
        P('And in the last five years — accelerated by COVID, the rise of DIY marketing platforms, and the explosion of AI tools — we’ve seen an influx of well-meaning but under-experienced consultants stepping into the industry. They may be charismatic and visible, but they often lack the depth and breadth that real marketing leadership requires.'),
        H('Why This Matters for Business Owners'),
        P('When you hire someone to guide your marketing, you’re not just hiring them to post pretty content or set up a quick campaign. You’re trusting them with something much bigger: the growth engine of your business. The kind of marketing leadership that actually moves the needle requires:'),
        L([
          'Professional training. Marketing isn’t just a skill you pick up on YouTube. It’s a discipline with decades of research, best practices, and evolving frameworks — often studied formally through degrees, MBAs, or certifications.',
          'Decades of hands-on experience. Real marketing expertise is forged in the trenches — designing campaigns, managing budgets, testing strategies, failing, learning, and ultimately delivering results across industries. You don’t gain that depth in five years. You gain it in twenty or thirty.',
          'Full-customer-journey perspective. Marketing is more than “getting attention.” It’s about attracting, converting, and retaining customers. A true expert knows how to build a system where every touchpoint — from awareness to loyalty — works together to create sustainable growth.',
          'Proven results across industries. Trends change, but principles remain. An experienced marketer has adapted strategies for small businesses, large corporations, B2B, B2C, and nonprofits. That adaptability is what makes their guidance resilient and trustworthy.',
        ]),
        H('The Rise of the Post-COVID “Marketing Expert”'),
        P('The pandemic created an interesting shift. Many people were laid off, started side hustles, or leaned into entrepreneurship for the first time. At the same time, easy-to-use DIY tools exploded — platforms like Canva, Mailchimp, Squarespace, and TikTok made it simple for anyone to start “doing marketing.”'),
        P('And that’s not a bad thing. These tools democratized marketing and gave small businesses affordable ways to show up online. But it also blurred the lines between someone who knows how to use a tool and someone who knows how to lead a marketing strategy. The danger for business owners is this: a shiny social media presence doesn’t always equal business growth. You can be active online, even popular, and still struggle to attract, convert, and retain paying customers. That’s why it’s so important to discern who you trust with your marketing.'),
        H('What to Look For in a True Marketing Partner'),
        P('If you’re considering hiring a marketing consultant, coach, or fractional CMO, here are four qualities that signal real expertise:'),
        L([
          'They’ve owned or run a business. It’s one thing to advise from theory; it’s another to carry the weight of payroll, client retention, and growth.',
          'They understand the full journey. Ask how they approach awareness, conversion, and retention. If they can only talk about social media or ads, that’s a red flag.',
          'They have proven results in multiple industries. Someone with a wide portfolio of clients will know how to flex strategies to fit your unique context.',
          'They are professionally trained. Look for formal education in marketing — a degree, MBA, or specialized certifications — so they can blend timeless principles with current trends.',
        ]),
        H('The Blend That Works'),
        P('The most effective marketing leaders don’t rely only on what’s trendy, nor do they get stuck in outdated models. They know how to blend the timeless best practices that have stood for decades with the fresh trends that capture today’s audiences. That’s what creates a marketing system that’s not just flashy, but sustainable.'),
        H('A Final Word'),
        P('As a business owner, you deserve more than a tactic. You deserve a partner who brings wisdom, training, and experience to the table — someone who can help you build a growth engine that lasts. So before you hire your next “marketing expert,” look beyond the title. Look for the track record and the training. Your business depends on it.'),
      ],
    },
    {
      title: '“It’s Not Working.” Now What?',
      cat: 'Strategy', date: 'Jul 30, 2025', sort: 20250730, read: '7 min read',
      tags: ['#Marketingmadesmarter', '#Lauracapesterrymba'],
      img: 'blog/its-not-working.webp',
      dek: 'Why that frustrating moment might be the start of your smartest strategy yet. “It isn’t working” is rarely the end of a story — it’s the beginning of a smarter one.',
      body: [
        P('When a client says, “My marketing just isn’t working,” I don’t panic. I pause. Because “it’s not working” isn’t the end of a story — it’s the beginning of a smarter one.'),
        P('It’s not failure. It’s feedback. It’s an opportunity to pause, reflect, and realign. And it’s almost never caused by a single issue.'),
        P('That’s why when someone comes to me with frustration, I become a detective. I peel back the layers. I ask questions. And I dig until I understand the why — so we can decide what to do next with clarity and confidence. Here’s where I begin:'),
        H('1. Expectations: What Does “Working” Really Mean?'),
        P('Before I look at any numbers, platforms, or creative, I ask one critical question: What were you expecting this campaign to do? Was the goal brand awareness, lead generation, or sales? Were those outcomes realistic given the timeline, budget, and platform? Was this campaign part of a larger strategy or standing on its own? One of the biggest reasons a campaign “doesn’t work” is because the expectations were never clearly defined — or they were misaligned with what that campaign was designed to do.'),
        H('2. Strategy: Is the Foundation Sound?'),
        P('Once expectations are clear, I zoom out. Because every campaign should be rooted in a bigger picture. Does this tactic support your long-term marketing goals? Is it integrated into a broader brand strategy and customer journey? Are we layering efforts in a way that builds momentum — or are we just chasing quick wins? Good marketing isn’t just reactive. It’s strategic, intentional, and cumulative.'),
        H('3. Audience: Are We Reaching the Right People?'),
        P('Even the best message won’t move the needle if it’s landing in front of the wrong people. Are we clear on your best-fit customer? Are we targeting the right geographic area and demographic? Are we reaching people who are ready to act — or people who just happen to scroll by? Sometimes a small adjustment to targeting or timing makes all the difference.'),
        H('4. Creative & Design: Does It Build Trust and Connection?'),
        P('Design isn’t just about looking good — it’s about feeling real, credible, and human. Does the creative reflect your voice, your values, and your expertise? Is it clear and emotionally engaging? Does it inspire trust — or create doubt? Are we using authentic visuals and messaging or generic, AI-generated content that falls flat? Creative that misses the mark doesn’t just underperform — it can actually hurt your brand.'),
        H('5. Performance & ROI: Are We Measuring What Matters?'),
        P('Finally, I look at results — but not just surface numbers. Are we tracking meaningful metrics based on your actual goals? Are we evaluating the campaign over a realistic time frame? Are we assessing total impact — not just clicks or impressions? Are we accounting for momentum and brand lift, not just instant conversions? Marketing isn’t one moment. It’s a journey. And sometimes, what looks like a failure is actually the beginning of a long-term win.'),
        H('A Real Example from My Work'),
        P('A client recently came to me frustrated with an OTT campaign — those commercials that play on streaming services. He said, “It’s not working. Let’s shut it down.” But instead of pulling the plug right away, I asked for permission to dig. And here’s what I found: the audience targeting needed refinement, the creative was built with AI and lacked warmth and connection, and the agency was delivering impressions but not connection. So yes, the campaign was “running.” But it wasn’t working.'),
        P('We ultimately made the call to pause the ads — not because the strategy wasn’t smart, but because we needed to get the creative, the message, and the execution on brand before it made sense to invest those valuable dollars in the advertising.'),
        H('The Bottom Line'),
        P('You can’t just label something “isn’t working” without understanding the complexity of what that means. Marketing is part art and part science. And when something goes off track, it doesn’t mean you’ve failed. It just means there’s something that needs attention. That’s what I do: I bring three decades of hands-on experience to help you pause, ask better questions, and get to the root of what’s really happening — so we can move forward with clarity, confidence, and smarter strategy.'),
        Q('So if something in your marketing feels off? Reach out. Let’s get curious — and then let’s get you back on track.', 'Laura Capes Terry, MBA'),
      ],
    },
    {
      title: 'The Unbridled Creative Podcast - Launching Fall 2025!',
      cat: 'Podcast', date: 'Jul 14, 2025', sort: 20250714, read: '4 min read',
      tags: ['#Theunbridledcreative', '#Podcastepisode'],
      img: 'blog/unbridled-fall-2025.png',
      dek: 'Real, raw, and redemptive stories of people who have broken free — and chose courage, faith, and clarity to leap into a life they designed on their own terms.',
      body: [
        P('The Unbridled Creative Podcast — hosted by Laura Capes Terry & Trent Soles.'),
        P('The Unbridled Creative podcast exists to tell real, raw, and redemptive stories of people who have broken free — from corporate jobs, fears, limiting beliefs, physical limitations, time constraints, or financial barriers. These are the Unbridled Creatives — people who once felt fenced in, but chose courage, faith, and clarity to leap into a life they designed on their own terms.'),
        H('This podcast is equal parts inspiration and action'),
        P('Each episode delivers:'),
        L([
          'Stories of breakthrough: how everyday people — often guided by God’s hand — have traded constraint for creativity and fear for freedom.',
          'Faith-fueled encouragement: reminders that your calling is real, your gifts matter, and the Creator wired you to create.',
          'Practical guidance: strategies in marketing, media, and the entrepreneurial mindset to equip listeners for the journey ahead.',
        ]),
        P('At its core, The Unbridled Creative is a movement for those with an entrepreneurial itch and a heart for freedom. It’s for those who feel the tug to do something more, but aren’t sure where to start. Laura Capes Terry and Trent Soles, as the original Unbridled Creatives, know the joy that comes with being in charge of your time, income, values, and direction — and they want that for others.'),
        P('Whether you’re sitting at a desk dreaming of something more, or you’ve already taken your first steps into freedom, this podcast is here to inspire, empower, and equip you to jump your fence and run unbridled toward the life you were made for.'),
        P('Sign up to receive our launch announcement at www.theunbridledcreative.com.'),
      ],
    },
    {
      title: 'Why I’m All In on the New StoryBrand Coach Direction (And Why You Should Be Too)',
      cat: 'StoryBrand', date: 'Jun 07, 2025', sort: 20250607, read: '6 min read',
      tags: ['#Storybrand', '#Lauracapesterrymba'],
      img: 'blog/storybrand-coach.png',
      dek: 'StoryBrand Certified Guides are now StoryBrand Certified Coaches. It may seem like a subtle shift in title, but it marks a major evolution in how we serve business owners.',
      body: [
        P('If you’ve followed the StoryBrand world for a while, you’ve probably heard the news: we’re no longer just StoryBrand Certified Guides — we’re StoryBrand Certified Coaches. And while that may seem like a subtle shift in title, it marks a major evolution in the way we serve business owners.'),
        P('For years, being a StoryBrand Guide meant honing the skill of copywriting through the lens of a proven messaging framework. And while that framework — based on the power of story to cut through noise and connect with customers — remains rock solid, the role is expanding. It’s no longer just about writing clear copy. It’s about helping businesses make clear marketing decisions. This is a shift I’ve been waiting for.'),
        H('Not Just a Guide — A Strategist'),
        P('The truth is, I’ve been doing strategy and coaching for businesses for decades. Long before “fractional CMO” was a familiar term, I was walking into businesses, assessing their gaps, building roadmaps, and guiding execution. In fact, I introduced myself as a fractional CMO six years ago to someone who responded with, “What’s that?” Fast forward to today, and StoryBrand is telling the world exactly what I’ve always believed: that businesses don’t just need another piece of content — they need clarity, leadership, and a smart, cohesive strategy to move forward.'),
        P('That’s why this new chapter of StoryBrand feels like home. It’s finally congruent with who I am and what I’ve always brought to the table.'),
        H('Why Some Are Leaving (And Why I’m Not)'),
        P('I understand why some certified guides are stepping away. Not everyone feels comfortable moving from copywriter to coach. Coaching requires a broader skill set — business acumen, marketing experience, and leadership that stretches beyond a sales page or website wireframe.'),
        P('But here’s the thing: business owners don’t just need writers. They need guides who can lead. They need someone who understands the whole picture — market, message, media, and moment — and can craft a plan that works. That’s the kind of impact I want to make, and why I’m leaning in, not out.'),
        H('This Isn’t Just Certification — It’s Confirmation'),
        P('To be honest, I’ve considered not renewing my certification in the past. Not because I don’t believe in the framework — I absolutely do — but because I’ve already mastered it. I didn’t need the credential to serve my clients well. But I’ve always appreciated the authority and credibility it brings.'),
        P('Now, StoryBrand is aligning more than just messaging — it’s aligning mission. We’re being positioned as fractional marketing leaders, not just tacticians. And that gives me even more confidence to stand tall in my expertise and support my clients in a deeper, more transformative way.'),
        H('Helping You Market with Clarity, Confidence, and Impact'),
        P('So, what does this mean for you? It means that if you’re tired of throwing spaghetti at the wall with your marketing… if you’re sick of guessing which tactic to try next… if you’re looking for someone to walk alongside you, help you see the big picture, and create a clear path forward that’s actually doable… then you don’t just need a copywriter. You need a coach.'),
        P('As a StoryBrand Certified Coach and fractional CMO with 30 years of experience, I’m here to help you clarify your message, design a strategy that fits your business, and execute with confidence. The future of StoryBrand is strategic — and I’m here for it.'),
      ],
    },
    {
      title: 'Clarify Your Brand’s Message and Attract Your Ideal Audience',
      cat: 'Podcast', date: 'Apr 25, 2025', sort: 20250425, read: '3 min read',
      tags: ['#Podcastepisode'],
      img: 'blog/your-brand-backyard.jpg',
      dek: 'On the Your Brand, Your Backyard podcast: how message clarity and hyper-local strategy can dramatically transform how small businesses connect with their ideal clients.',
      body: [
        P('In this podcast episode, Julie and Jeremy sit down with Laura Terry — an energetic local business advocate, owner of BeLocal Georgetown, and a certified StoryBrand Guide. Laura shares how the combination of message clarity and hyper-local strategy can dramatically transform how small businesses connect with their ideal clients.'),
        P('Laura walks us through the core of the StoryBrand framework and explains why confusing marketing messages cost businesses money and momentum. She shares powerful stories of businesses that clarified their message and used BeLocal to get in front of the right people — especially new movers making big purchasing decisions.'),
        P('Whether you’re just starting out or looking to scale with intention, Laura’s insights will help you sharpen your message, stand out locally, and build a brand that truly resonates.'),
        P('Listen to the full episode on the Your Brand, Your Backyard — Local Business Podcast (Season 1, Episode 11).'),
      ],
    },
    {
      title: 'Why Most Businesses Are Measuring ROI All Wrong',
      cat: 'Strategy', date: 'May 08, 2026', sort: 20260508, read: '7 min read',
      tags: ['#Lauracapesterrymba', '#Marketingmadesmarter'],
      img: 'blog-roi-cover.png',
      dek: 'What if your marketing is actually working — but you’re measuring the wrong version of ROI?',
      body: [
        P('It’s one of the most common frustrations I hear from business owners:'),
        Q('I spent money on marketing, but I didn’t get any ROI.'),
        P('And honestly? I understand why people feel that way. When business owners invest in marketing, they naturally want to know: Did it work? Did it generate leads? Did I get my money back?'),
        P('But here’s the problem: most businesses are only measuring the final transaction while ignoring everything that made the transaction possible. And that’s where so many good businesses start making bad marketing decisions.'),
        H('Marketing Is Not a Vending Machine'),
        P('Somewhere along the way, business owners were taught to think about marketing like this: put money in, get customers out. But that’s not how real marketing works.'),
        P('Marketing is much more like going to the gym. You don’t work out one time and suddenly become strong. You don’t eat one healthy meal and suddenly become healthy. You build strength through repetition. Consistency. Visibility. Trust. Momentum.'),
        P('Marketing works the same way. Every touchpoint matters. Every interaction matters. Every impression matters. And many of the most important things happening in your marketing are happening before the sale ever occurs.'),
        H('The Problem With Measuring Only Transactions'),
        P('Most businesses only measure lagging indicators:'),
        L(['leads', 'phone calls', 'sales', 'revenue']),
        P('Those things matter, of course. But if those are the only things you measure, you miss the entire buyer journey that made the sale possible.'),
        P('Think about your own buying behavior for a moment. How often do you:'),
        L(['notice a business several times before calling them?', 'read reviews before making a decision?', 'visit someone’s website multiple times?', 'follow them on social media for weeks or months?', 'ask a friend if they’ve heard of them?', 'quietly observe how they show up online?']),
        P('That process matters. Trust takes time to build. And most customers are making decisions long before they ever reach out.'),
        H('The Iceberg Effect of Marketing ROI'),
        P('I often think about marketing like an iceberg. The sale is the tiny visible piece above the water. But underneath the surface are all the things that made that sale possible:'),
        L(['brand awareness', 'familiarity', 'consistency', 'trust', 'referrals', 'engagement', 'timing', 'emotional connection']),
        P('The challenge is that many of those things are difficult to measure precisely. That doesn’t mean they aren’t working. It simply means marketing is more human and more nuanced than a spreadsheet can fully capture.'),
        H('Why Marketing Attribution Is So Difficult'),
        P('Business owners often ask, “How did they find us?” And sometimes the customer says: Google, Facebook, a friend, your podcast, your website.'),
        P('But the reality is usually much more layered than that. Maybe they:'),
        L(['saw your logo on a truck', 'heard your name at a networking event', 'saw your social posts for six months', 'read reviews', 'drove past your sign', 'listened to a podcast interview', 'received a referral', 'visited your website three different times']),
        P('Then finally… they Googled you. So what actually caused the sale?'),
        Q('Marketing works cumulatively. It’s rarely one thing — it’s the layered effect of visibility, trust, consistency, and timing working together over time.', 'Laura Capes Terry, MBA'),
        H('The Leading Indicators Most Businesses Ignore'),
        P('Instead of only asking, “Did I get a sale?” smart businesses also ask:'),
        L(['Are people seeing us?', 'Are people engaging with us?', 'Are people recognizing our name?', 'Are more people visiting our website?', 'Are we building trust in the community?', 'Are we showing up consistently?']),
        P('Those are called leading indicators, and they usually happen before the revenue follows. That’s why businesses often quit too early — they stop planting seeds before they’ve had time to grow.'),
        H('Real ROI Is Bigger Than a Single Sale'),
        P('The businesses winning today understand something important: marketing is not just about generating transactions. It’s about creating visibility, trust, credibility, and connection before someone is ready to buy. Because when the right moment finally arrives, people choose the business they already know and trust. That’s real ROI.'),
        H('Final Thoughts'),
        P('If you’ve been discouraged because your marketing hasn’t produced instant results, I want to encourage you not to panic too quickly. Step back and ask yourself:'),
        L(['Am I building visibility?', 'Am I building trust?', 'Am I showing up consistently?', 'Am I getting in front of the right people in the right places?', 'Am I planting seeds that will grow over time?']),
        P('Because if the answer is yes… your marketing may be working far more than you realize. Sometimes the sale is simply the final chapter of a much longer story.'),
      ],
    },
    {
      title: 'What Can Local Businesses Learn from the Big Brands Advertising in the Super Bowl?',
      cat: 'Local Marketing', date: 'Mar 11, 2025', sort: 20250311, read: '4 min read',
      tags: ['#Georgetownchamber', '#Graysonmediagirls', '#Lauracapesterrymba'],
      img: 'blog/super-bowl-mastermind.png',
      dek: 'You don’t need a Super Bowl budget to market like the big guys — you just need smart strategies. Here are seven advertising lessons every local business can use.',
      body: [
        P('Every year, the world’s biggest brands spend millions of dollars for a 30-second Super Bowl commercial — but why? And what can a local business in a small town learn from these massive advertising campaigns? The truth is, you don’t need a Super Bowl budget to market like the big guys — you just need smart strategies.'),
        P('Here are 7 powerful advertising lessons from Super Bowl advertisers that every local business can use:'),
        H('1. Tell a story, not just sell'),
        P('Super Bowl ads don’t just promote products; they create emotional connections through storytelling. Local businesses should share their journey, their impact on the community, and the people behind the brand.'),
        H('2. Make your message simple & clear'),
        P('Big brands focus on one core message in their ads. Local businesses should avoid overloading ads with too much info — stick to one powerful idea that customers can easily remember.'),
        H('3. Be consistent across all platforms'),
        P('Super Bowl advertisers use multiple channels (TV, social media, billboards) to reinforce their message. Local businesses should do the same with a mix of print, digital, and community engagement to stay top-of-mind.'),
        H('4. Use humor & emotion'),
        P('The most memorable Super Bowl ads make people laugh, cry, or feel inspired. A local business can stand out by adding personality, humor, or heartfelt storytelling to its marketing.'),
        H('5. Create a strong call-to-action'),
        P('Super Bowl ads aren’t just for entertainment — they drive action. Make sure your local ads tell customers exactly what to do next (Call Now, Visit Today, Book an Appointment, Follow Us).'),
        H('6. Leverage social media to extend your reach'),
        P('Super Bowl ads don’t stop at TV — they go viral on social media. Local businesses should use video content, shareable posts, and community engagement to maximize their visibility.'),
        H('7. Invest in visibility — be seen everywhere'),
        P('Super Bowl brands pay big money for attention because they know visibility = sales. Local businesses must invest in smart advertising (print, social media ads, sponsorships) to stay top-of-mind in their community.'),
        Q('Bottom line: you don’t need millions to market like a Super Bowl brand — just a smart strategy and consistent visibility in your local market.', 'Laura Capes Terry, MBA'),
        P('What’s YOUR biggest takeaway from Super Bowl ads?'),
      ],
    },
    {
      title: 'How to Create Ads with Impact',
      cat: 'Ad Design', date: 'Jun 05, 2024', sort: 20240605, read: '6 min read',
      tags: ['#Ad-Design', '#Belocal'],
      img: 'blog/ads-impact.png',
      dek: 'Some print ads grab the eye of every reader and leave a positive, memorable impression. Not-so-great ads can be seen but forgotten. Here’s how to make sure yours gets noticed.',
      body: [
        P('Not all ads are created equal. Some print ads grab the eye of every reader and leave them with a positive, memorable impression. Not-so-great ads can be seen but forgotten. I want BeLocal readers to notice and appreciate your ads.'),
        P('Unlike some of the “spray and pray” methods of marketing which blast out to a lot of uninterested people (aka a lot of waste), you know your ads are seen by BeLocal readers because our content is so intimate, local, and relevant to them. In other words, it’s even more important that your ad makes an impression since the right people are actually seeing it.'),
        P('Maybe you’ve already got the perfect ad that tells your story and shows you’re a reputable business. When the need arises, readers are already aware of you as a community supporter and a local company they can trust. Kudos!'),
        P('If you think your ad leaves something to be desired, I want to share some great tips from April. She works in the ad design team at BeLocal. Remember, a perk of this advertising program is the ability to update your ad, so please reach out to me if any of these ideas spark inspiration.'),
        Q('An advertisement’s job is not to provide all possible information about the client, but rather, it first needs to grab the reader’s attention. This can be done with less ‘clutter’ in the ad, a catchy headline, some bold imagery, and using these elements to share how the client stands out from the competition.', 'April, BeLocal ad design team'),
        H('Tip #1: Let a photo dominate'),
        P('One of the design trends this year is prominent photography. When our design team is given a great image from a client — or we find that perfect stock image — we know we can knock the design out of the park. Prominent photography can evoke a certain mood and tone in the ad, making readers want to take action. It also allows the ad to speak for itself without the need for too much text — ad copy should ideally take up less than a third of the ad space. Find the perfect singular photo that grabs the attention of our readers and communicates what you’re all about, so less copy is necessary.'),
        H('Tip #2: Go natural'),
        P('Another design trend is using natural materials to evoke emotional appeal. Natural materials often bring to mind positive emotions such as warmth, comfort, and nostalgia. By incorporating these materials into ad design, brands can tap into these emotions and create a deeper connection with their audience. Examples include images of nature (trees, sunlight, grassy fields, water), or using a natural texture as the background of the ad (wood paneling, stones, brick, etc.).'),
        H('Tip #3: Feature a reader'),
        P('To quickly build trust among readers, use your ad space to tell them you’ve already been “chosen” by some of their fellow residents. You can do this by showing a map of recent projects in the community, featuring a resident’s project in the ad, or including a testimonial from a resident or other high-profile local influencer.'),
        H('Additional quick tips'),
        L([
          'Take your current headline and brainstorm catchier or more impactful versions of it.',
          'Consider creating an ad campaign (a series of related ads) instead of a one-off ad — use the same messaging and theme but switch out the image or feature a new reader testimonial.',
          'Think about what these specific readers want, need, and value (a high-end experience, supporting local, etc.) when you consider the look and feel of your ad.',
          'Keep in mind our readers can afford your services, so it’s better to use the ad space to tell them why you’re better than the competition instead of discounts or promotional call-to-action sections.',
          'Create a seasonal ad if it makes sense for your business, but do so purposefully (don’t just add an American flag to your ad and call it a Fourth of July version).',
        ]),
        P('I want your ad to be noticed and appreciated! Email me at laura@lauracapesterry.com for a free ad design handbook to help you create your next print ad.'),
      ],
    },
    {
      title: 'Spotlight on Laura Capes Terry',
      cat: 'Press', date: 'Mar 05, 2023', sort: 20230305, read: '4 min read',
      tags: ['#Lauracapesterry'],
      img: 'blog/schooley-mitchell.png',
      dek: 'Here’s the Schooley Mitchell spotlight on Laura Capes Terry — a career marketer helping local businesses make smarter marketing decisions.',
      body: [
        P('In the past few years, the way small businesses market themselves has had to change. For many business owners, it’s hard to meet the challenges posed by new marketing methods while still dedicating their time and effort to the work they do best. That’s where Laura Capes Terry comes in.'),
        Q('I’m a career marketer. I’ve done it my whole life. I help local businesses make smarter marketing decisions.', 'Laura Capes Terry, MBA'),
        P('Capes Terry got her start in marketing while at the University of Iowa. Drawn to the creativity and expression made possible through ever-evolving marketing channels, she found her niche in the business world, and hasn’t looked back since. Today, with three decades of experience behind her, she is a StoryBrand Certified Marketing Guide, a certified partner for DigitalMarketer, and has won countless awards for excellence in her field.'),
        P('For eight years now, Capes Terry has embraced entrepreneurship and works as an independent marketing and media consultant who offers fractional CMO services to local businesses. Some of these services include brand refresh and design, web design, copywriting, SEO, marketing workshops, and more.'),
        P('Capes Terry also owns two magazines, BeLocal Cedar Park Leander and BeLocal Georgetown, both of which connect new residents to the local providers they need. Not only do residents benefit from these publications, but they also allow businesses to advertise hyperlocally on a widespread multimedia platform.'),
        P('As a business owner herself, Capes Terry knows exactly what it takes to make the most of her marketing dollars, even in challenging economies like we’ve faced in the past few years.'),
        Q('I have a lot of empathy for my clients that are running businesses, because I know what it means to be responsible for a P&L.', 'Laura Capes Terry, MBA'),
        P('She spends a lot of her workdays in conversation with other entrepreneurs, getting to know their needs, their business, and their goals. Taking this individualized approach to each client allows Capes Terry to truly serve every local business she works with, developing a strategy that best suits their wants and needs.'),
        P('In today’s economy, small businesses need every advantage they can get. Without a doubt, Capes Terry gives them a huge boost and an ally they can count on.'),
        P('For more information, visit her website at www.lauracapesterry.com. Follow Laura on Instagram: @lauracapesterrymba.'),
      ],
    },
    {
      title: 'Newcomer Guide “BeLocal” Coming to Georgetown',
      cat: 'BeLocal', date: 'Jan 23, 2022', sort: 20220123, read: '7 min read',
      tags: ['#Belocalgeorgetown', '#Gtxnewcomers', '#Hellogeorgetown'],
      img: 'belocal-georgetown-cover.jpg',
      dek: 'A newcomer guide aimed at helping new move-ins and long-time residents alike is coming to Georgetown. Here’s the story behind it.',
      body: [
        P('A newcomer guide aimed at helping new move-ins and long-time residents alike is coming to Georgetown!'),
        P('Laura Capes Terry, owner of BeLocal Georgetown, told Hello Georgetown she is looking forward to providing a guide that connects new residents with the best resources in town — like Hello Georgetown, the Georgetown Chamber of Commerce, the Visitor’s Center, and local businesses who can help them settle into their new home and new city with ease.'),
        P('Hello Georgetown is teaming up with BeLocal to provide new residents and longtime residents this resource, and we sat down with Laura Capes Terry to talk about why she decided to bring it to the community.'),
        H('What is BeLocal?'),
        P('BeLocal is a national brand that creates hyperlocal newcomer guides for over 100 of America’s top cities. Here in the Austin area, we currently have a BeLocal in Cedar Park, Southwest Austin, and West Austin — with plans to open a BeLocal in Georgetown in 2022.'),
        P('These comprehensive local resource guides are available in print and online. What makes them special is that they’re written by long-time locals to introduce newcomers to important local resources, top attractions, hidden gems, and insider tips.'),
        P('BeLocal Georgetown is 100% funded by reputable local businesses that want to be the first in their industry to connect with new residents moving to Georgetown. Since BeLocal arrives in the new resident’s mailbox shortly after they move into their new home, our business partners get the first chance to build a life-long relationship with each family.'),
        P('This is a unique window of time for our local business community as these new movers are actively seeking local products and services. And because BeLocal is a trusted resource guide, our business partners are seen as trusted community partners — not solicitors.'),
        H('Here’s how it works'),
        P('We use the power of word-of-mouth and local recommendations to produce an essential local resource guide for new movers. Our goal is to ease the transition and cut years off the time it takes for these new residents to feel like a local.'),
        P('Then, we mail a printed copy of the guide to new residents shortly after they move into their new homes. This guide is beautifully designed and filled with important resources, so it typically remains on the family’s countertop or coffee table for several months. We also make our content available online 24/7 so anyone has access to this important information.'),
        H('What sparked your decision to bring BeLocal to Georgetown?'),
        P('As a member of the Georgetown Leadership Class of 2021–2022 (put on through the Georgetown Chamber of Commerce), our class was asked to read a very special book called “The Power of Moments” by brothers Chip and Dan Heath.'),
        P('This book fascinated me. It explores why certain brief experiences can jolt us, elevate us, and even change us — and it inspired me to learn how to create such extraordinary moments in my own life and work.'),
        P('Then our class had the unique pleasure of hearing Hugh Brown, CEO of St. David’s Georgetown, speak on “The Power of Moments.” He showed us how we can proactively become the authors of these defining moments by focusing on three situations: transitions (moving from one stage to the next), milestones (achievements that can be marked), and pits (negative experiences that can be reshaped).'),
        P('The most impactful moment for me came at the end of his presentation when he challenged us: “As leaders in Georgetown, what can we collectively do to elevate the city and make this an even greater place to live?” In that moment, I felt God’s whisper… create a newcomer guide for Georgetown.'),
        H('What do you hope Georgetown residents will gain?'),
        P('For new residents, my hope is to use the power of our platform to mark the moment of arrival and make their transition magical, easy, and memorable. By working together, our community can:'),
        L([
          'Proactively welcome new residents shortly after they move in, so they feel noticed and cared about.',
          'Quickly introduce them to the most important resources they’ll need to settle in, so they connect to others and quickly feel like a local.',
          'Share the heart of Georgetown with newcomers when they first arrive, so they feel warm about this place they’ve chosen to call home.',
          'Give new residents an essential resource they’ll rely on for months — and a keepsake they’ll treasure.',
        ]),
        P('For our long-time residents, my hope is that our mission makes you proud. By collaborating with our city’s best resources — Hello Georgetown, the Georgetown Chamber of Commerce, Leadership Georgetown, the Visitor’s Center, the City of Georgetown, and more — we can add tremendous value to the lives of new residents, help them feel welcomed and connected, and pass on the history and heart of Georgetown for generations to come.'),
        H('What are you most excited about?'),
        P('Relocating is not easy. When my family and I first moved here from Austin, it was an overwhelming experience. I wished someone had given me a resource like BeLocal when we first arrived, so we didn’t have to struggle to plug in and find essential resources.'),
        P('Now that I live here, what I’m most excited about is connecting the dots for new residents in Georgetown — being the trusted resource I wish I’d had delivered to my mailbox, so they can quickly plug in and feel like a local.'),
        P('Laura Capes Terry, owner of Grayson Media & Marketing, is an MBA, StoryBrand Certified Marketing Guide, and Certified Partner for DigitalMarketer. Working as a marketing and media consultant, Laura helps small, local business owners attract and engage their ideal clients through traditional and digital marketing strategies.'),
      ],
    },
    {
      title: 'Bring it on, 2022!',
      cat: 'Reflection', date: 'Jan 01, 2022', sort: 20220101, read: '4 min read',
      tags: ['#2021review', '#2022'],
      img: 'blog/bring-it-on-2022.png',
      dek: 'No doubt… 2021 was a beast. But like many of us, I used it to get stronger and smarter — and now I’m ready for 2022.',
      body: [
        P('No doubt… 2021 was a beast. But like many of us, I used it to get stronger and smarter.'),
        P('For me, I used 2021 to immerse myself as a student of post-Covid digital marketing strategies. I went back to my “roots” as a marketing consultant and CMO for small, local businesses to rebrand and sharpen my saw. And I built an arsenal of post-Covid client success stories.'),
        P('Now, I’m ready for 2022. Now, I’m confident and equipped to help our local businesses survive and thrive in the complex world of digital marketing.'),
        P('Now, BeLocal (Greater Cedar Park) is just one of the tools in my toolbox to help our local businesses connect to their ideal clients so they can survive and thrive in a post-Covid world.'),
        P('Now, as a StoryBrand Certified Guide and Certified Partner for DigitalMarketer, I can act as a full-service boutique marketing agency… building killer websites, running powerful SEO & SEM campaigns, building attention-grabbing lead magnets, and building state-of-the-art (StoryBranded) email nurture campaigns and sales funnels.'),
        Q('Bring it on, 2022. I’m ready for you… so are my clients.', 'Laura Capes Terry, MBA'),
        P('Thank you to Brittany Horn for being my beacon of light in 2021, to Lauri Zachry Truong for being my right arm, to April Aguren for being a great friend, to Donald Miller and the folks at StoryBrand for teaching me state-of-the-art messaging strategies, and to Mark de Grasse and the folks at DigitalMarketer for equipping me with state-of-the-art digital marketing strategies to help my clients succeed in a post-Covid world.'),
        P('One of the things 2021 taught me is that no matter how hard we work, the target will keep moving… so then, so will I.'),
        H('Two free resources to rock your 2022'),
        P('For you business owners out there, I have a couple of great FREE resources I can share to help rock your marketing in 2022:'),
        L([
          '6 tips to make over your home page so you can attract and engage more of your ideal clients — because you work too hard to drive traffic to your website just to watch it bounce when people are confused by your message.',
          '12 secrets to great ad design so you can get noticed and make an impact — because advertising only works when your message is relevant, clear, and resonates emotionally with your ideal client.',
        ]),
        P('Email me at laura@lauracapesterry.com and I’ll be happy to send you these free resources. To our local business owners: I’m rooting for each of you! Cheers to your success in 2022!'),
      ],
    },
    {
      title: 'Meet Laura Capes Terry',
      cat: 'Press', date: 'Sep 04, 2021', sort: 20210904, read: '9 min read',
      tags: ['Austin Hidden Gems', 'Grayson Media & Marketing', 'Voyage Austin'],
      img: 'blog/meet-laura-voyage.png',
      dek: 'As seen in Voyage Austin — the story behind three decades of marketing, the fitness industry, BeLocal, and the fire to help local businesses thrive.',
      body: [
        P('As seen in Voyage Austin. Today we’d like to introduce you to Laura Capes Terry.'),
        H('Thanks for joining us — start by introducing yourself.'),
        P('My name is Laura Capes Terry. I grew up in a small town outside of Chicago called Elburn, IL. After graduating from the University of Iowa, I was one of the lucky graduates that got to work in the profession.'),
        P('I spent the first five years of my career working as a Marketing Manager for a commercial printing company outside of Chicago called ABS Graphics. I learned so much there — graphic design, marketing, media, PR, communications, printing, technology, sales, customer service, and business operations. It was a great learning experience, and I’m grateful to all the seasoned pros who mentored me.'),
        P('During those five years, I put myself through grad school earning my MBA from Northern Illinois University, won a Benny Award for Innovative Marketing from the National Association of Printers and Lithographers, and appeared on the cover of an industry magazine for helping reel in a giant client for the company: Walgreens.'),
        P('During the next chapter, I married my passion (fitness) with my profession (marketing) by going to work for Life Fitness as a Vertical Marketing Manager for the Platinum Dealer Network. When I first applied, they didn’t have a job opening — but they liked my passion for their industry and my track record, so they created the position for me.'),
        P('I spent almost two decades working in the fitness industry — one of the greatest and most rewarding chapters of my life. I worked with the world’s two largest fitness equipment manufacturers (Life Fitness and Precor) along with dozens of dealers across the U.S. and Canada. Most of these dealers were small, locally owned “mom and pop” shops without a seasoned marketing pro on staff. I had the honor of coming into their offices, magnifying their brand, and creating and executing marketing plans to grow their business. This is where I proved myself as a female marketer and entrepreneur in a male-dominated industry.'),
        Q('Your path should inspire women who wish to be successful in a male-dominated industry and men who want to understand what working with a pro who commands respect and is amazing at their craft can do for the bottom line.', 'Guy Williams, Precor'),
        P('That chapter set me up for the one I live today: working as an entrepreneur and digital marketing consultant to help local business owners elevate their brand, magnify their impact, attract their ideal clients, and put more cash in their jeans.'),
        H('Has it been an easy path?'),
        P('The road certainly has not been smooth. Early in my career, I faced harassment, was undermined by colleagues, and was publicly betrayed by people closest to me in a way that forced me to sell my stock in my business. Looking back, if I’d known what was coming over the past three decades, I probably wouldn’t have started the journey — much less made it through, stronger on the other side.'),
        P('By the grace of God, I didn’t know what lay ahead. I just pushed through each challenge by trying to be who I am, follow God’s plan for my life, and be the example I want to be for my son.'),
        H('Tell us more about your business.'),
        P('Grayson Media is the marketing and media company I formed back in 2015. For 5.5 years, Grayson Media owned an N2 franchise called “Avery Ranch Living,” and more recently a second franchise, “BeLocal Greater Cedar Park” — a newcomer guide for Cedar Park serving local residents, businesses, and the Cedar Park Chamber of Commerce.'),
        P('Today, Grayson Media is much more than a publishing company. Since COVID, I’ve relaunched the consulting and coaching side of my business to help local owners get more from their marketing — private coaching, online courses, private workshops, and boutique agency services to help them elevate their brand, magnify their impact, attract ideal clients, and put more cash in their jeans.'),
        H('Anything else to share?'),
        P('I’ve been a StoryBrand Certified Marketing Guide for three years, and I’m a Certified Partner for DigitalMarketer — which allows me to bring proven frameworks tested by some of the world’s biggest brands to my local clients in an effective and affordable way.'),
        P('Finally, I’m also helping my son become an entrepreneur. He owns a business called GRT Cotton Candy Creations and provides made-to-order cotton candy for birthday parties and fundraisers. You can learn more about me at www.lauracapesterry.com and follow me on Instagram @lauracapesterrymba.'),
      ],
    },
    {
      title: 'Have you invested in marketing that isn’t getting a return?',
      cat: 'StoryBrand', date: 'Aug 11, 2021', sort: 20210811, read: '5 min read',
      tags: ['#Marketingplansmadesmarter', '#Storybrand', '#Storybrandlivestream', '#Storybrandmarketingworkshop', '#Vipcoaching'],
      img: 'blog/storybrand-workshop.png',
      dek: 'If you’re guessing at your next marketing move — or your website isn’t converting — a StoryBrand Marketing Workshop with VIP coaching may be exactly what you need.',
      body: [
        P('Have you invested in marketing that isn’t getting a return?'),
        L([
          'Are you guessing at what the next best step for marketing your business should be?',
          'Is your website not converting enough leads?',
          'Do you often stare at your social media feeds wondering what to write?',
          'Do you have a system for creating marketing materials that saves you time and money?',
        ]),
        P('If you’re struggling with any of these things, a StoryBrand Marketing Workshop is just what you need!'),
        P('Join Laura Capes Terry, a StoryBrand Marketing Guide since 2019, as she coaches a small VIP group of 4–6 local business owners through the StoryBrand Marketing LIVESTREAM led by Donald Miller on September 20–21, 2021, where you’ll create a clear message and a 5-part marketing plan for your business.'),
        H('After the event, you’ll walk away with…'),
        L([
          'A marketing message that unites your team and attracts your ideal clients to engage with your brand.',
          'An elevator pitch you can use in meetings, at parties, or on sales calls that makes people say, “Wow! Can I have your business card?”',
          'A website wireframe and sales funnel that will help you capture new leads and turn them into customers for life.',
          'A marketing plan that works — and the confidence that you’re doing it right.',
        ]),
        H('StoryBrand Livestream'),
        P('The StoryBrand Marketing LIVESTREAM is open to the public and anyone can register. Prior to COVID, this event cost $2,995 per person and required a trip to Nashville. Now you can attend from the comfort and convenience of your own home for only $995.'),
        H('VIP coaching plus StoryBrand Livestream'),
        P('For those who want a local, in-person VIP experience of the livestream, Laura Capes Terry (a StoryBrand Certified Marketing Guide) is offering VIP coaching before, during, and after the 2-day livestream to ensure you walk away with assets in hand that are ready to implement so you can grow your business with confidence.'),
        P('VIP Coaching is limited — only 4–6 local business owners here in Georgetown will be approved, and interested parties must apply and will be hand-selected by Laura to optimize the group dynamic. The VIP event will be held in the boardroom at the Georgetown Chamber of Commerce. For pricing and application details, please email laura@lauracapesterry.com.'),
      ],
    },
    {
      title: 'Let’s Celebrate Progress Over Perfection',
      cat: 'Inspiration', date: 'Mar 01, 2021', sort: 20210301, read: '2 min read',
      tags: ['#Bootcamp', '#Marketingmadesmarter', '#Marketingplansmadesmarter', '#Onlinecourse'],
      img: 'blog/journaling.jpg',
      dek: 'Do you keep a gratitude journal? Here’s why progress — not perfection — is worth celebrating.',
      body: [
        P('Do you keep a gratitude journal? I’ve found that keeping a gratitude journal can help me stay focused on what really matters in life… even when life is really hard and things feel upside down.'),
        P('Today, I wrote about how grateful I am to have overcome the bone-chilling shyness that shackled me as a child. It kept me from having friends, confidence, and self-esteem.'),
        P('That same girl just recorded hours of video for her new Marketing Plans Made Smarter Bootcamp and is putting her heart out on social media for the judgment of others.'),
        P('When I was young, just the idea of what I’m doing now would’ve made me throw up. I guess getting older has its perks.'),
        Q('What did you write about in your gratitude journal today?', 'Laura Capes Terry, MBA'),
      ],
    },
    {
      title: 'I Believe Life Happens For Us, Not To Us',
      cat: 'Inspiration', date: 'Feb 08, 2021', sort: 20210208, read: '3 min read',
      tags: ['#Inspiration'],
      img: 'laura-office-writing.jpg',
      dek: 'Very few people know this story. I’m sharing it because the experience helped shape me into the woman I am today — and I believe it can help someone else.',
      body: [
        P('Very few humans know this story. I’m sharing it now because this experience helped shape me into the woman I am today, and I believe my story can help someone else.'),
        P('Earlier in my career, when I was the co-owner of a chain of retail stores, I found out that the President of our company was sleeping with his secretary. (He was my husband. She was my friend.)'),
        P('Employees had been telling me for months not to trust her, but I didn’t want to believe that she — or he — could do that to me.'),
        P('But sure enough, on a fateful night in August of 2007, I learned the truth, and I had to face the fact that my life would never be the same again. In the end, I lost my husband and my friend. I also lost my company, my employees (who were friends), and my source of income.'),
        P('It was a very dark time.'),
        P('Some people told me to go on antidepressants. I said no. I told them I deserved to grieve. I decided that I was going to allow myself to feel the breadth and depth of the grief so that I could move through it, release it fully, and move on.'),
        P('I believe that wisdom came from the Grace of God, because making that decision was the moment I started to heal. Four months later, I was at Date With Destiny with Tony Robbins, designing the life I enjoy today.'),
        Q('Life happens FOR us, not TO us.', 'Laura Capes Terry, MBA'),
      ],
    },
    {
      title: 'When opportunity knocks, do you listen?',
      cat: 'Inspiration', date: 'Feb 02, 2021', sort: 20210202, read: '4 min read',
      tags: ['#Inspiration', '#Marketingmadesmarter', '#Whenopportunityknocks'],
      img: 'laura-candid.jpg',
      dek: 'The best opportunity I was ever given was one I almost turned down. Here’s what saying yes taught me.',
      body: [
        P('When opportunity knocks, do you answer? I think most of us would like to think we’d welcome a great opportunity with open arms… but it’s not always easy.'),
        P('In my career, the best opportunity I was ever given was the chance to relocate to the East Coast to serve as the Director of Marketing for a small mom-and-pop shop in the fitness industry.'),
        P('The owner had been my consulting client for six months and decided she wanted my time and attention — full time. The worst part was that I had to leave Austin, a city I loved. I did not want to move. I actually turned the opportunity down. But she made an offer I couldn’t refuse.'),
        P('So I moved to Maryland. It was supposed to be a 2-year gig. I started out as a one-woman show — with no support staff and no budget.'),
        P('Two years turned into six… and over that time, I helped her grow her business from 1 store to 18. My marketing budget grew from $0 to $1.6m, and my staff grew from 0 to 6. It was quite a ride.'),
        P('With a budget like that, I was called on by every media salesperson in town — so I spent a lot of time learning how to make smart media buying decisions. That job culminated in the opportunity to purchase a chain of fitness equipment stores here in Texas, which is what ultimately brought me back to Austin.'),
        P('I learned so much during those six years — about myself, about marketing mom-and-pop shops, and about being an entrepreneur. Today, I look back and feel so grateful that I opened that door when opportunity knocked, because it taught me so much and ultimately led me to where I am today… here with you.'),
        Q('What’s an opportunity you found difficult to accept?', 'Laura Capes Terry, MBA'),
      ],
    },
  ];

  posts.forEach(function (p) { p.slug = slugify(p.title); });
  window.LCT_BLOG = posts;
  window.LCT_BLOG_BY_SLUG = {};
  posts.forEach(function (p) { window.LCT_BLOG_BY_SLUG[p.slug] = p; });
})();
