/* Laura Capes Terry — Reviews / Testimonials */
(function () {
  const { Button, Pill } = window.LauraCapesTerryDesignSystem_1d8d61;

  const FEATURED = [
    ['Having been a client, a vendor partner, and a friend throughout your journey I can say that you are one of the best marketing executives I have ever worked with! Your path should inspire women who wish to be successful in a male-dominated industry and for men who want to understand what working with a pro who commands respect and is amazing at their craft can do for the bottom line!', 'Guy Williams', ''],
    ['Working with Laura has been a game-changer. Already having an established, successful small business, we initially thought we could manage the transition to an online presence and development of a marketing strategy ourselves. However, we’ve realized just how challenging and complex that process is — and how much we didn’t know. Since partnering with Laura, she’s been an invaluable guide, helping us identify and implement the right strategies for our needs. We only regret not reaching out to her sooner.', 'Wendy Del Re', ''],
    ['Since the very moment I met Laura, I knew I was in good hands. Not only is she incredibly knowledgeable on all things marketing, media, story-branding, and beyond, more importantly—she genuinely cares for business owners, and people. I have witnessed her interact with countless individuals, where she fully engages and empathizes with them. Laura isn’t here to sell you something you don’t need. She is here to serve you, and she does so very generously. If you need assistance with any marketing at all, Laura is my top recommendation!', 'Terry Wilkie', ''],
  ];

  const WALL = [
    ['Laura Terry is the real deal from marketing, growing your business, social media even reels! She is professional, customer service oriented, and truly knows her stuff! Top notch!', 'Sheila Evans'],
    ['As a new small business owner, I was spending so much money on marketing strategies and not getting a return on investment. I needed expertise in where and how to spend marketing dollars. Laura Capes Terry came highly recommended. From initial point of contact, Laura truly listened to my business needs, vision and came up with a game plan. My only regret is that I did not contact Laura sooner!', 'Anna Espinoza'],
    ['Laura is incredible! We had zero experience in marketing our businesses and had absolutely no idea where to start. We met with Laura and from the get go it was obvious she has seen companies like ours in this exact situation. She knew exactly what steps to layout for us to start our journey in building an online footprint for our company. I am literally able to see point A B And C of what tasks need to be accomplished to have our companies progress. Thank you Laura and your team!', 'Westley Heaney'],
    ['I can’t think of a better person or team with the insight and experience as a marketing consultant, media expert, and StoryBrand guide than Laura and her team. As a fellow business owner, I know how challenging it can be to establish a highly recognized and preferred presence in your field while effectively reaching your target market. Laura Capes Terry at Grayson Media & Marketing simplifies this process and makes it well worth the investment. The sustainable returns from the right brand message are invaluable. Highly recommend!', 'Trent Soles'],
    ['Lots of people can build a website or help you brand your business. Laura uniquely comes alongside and adds her years of experience, her caring nature and moves it from a good experience to a great experience. If you get the opportunity to have Laura come alongside and help you build our brand and web presence, you will stand well above the crowd. I have been around for a bit and know excellence when I see it.', 'Jack Stanley'],
    ['From the first time I met Laura, she’s been an angel in helping me get my company up and running. Up to this point, I haven’t been able to say no to her. Laura’s knowledge in the digital marketing space is second to none, she has truly been an asset for my small company to grow. From print ads to the digital space, her company has truly been able to transform my small company into what it will be down the road, a pillar of our community and a standout company to the industry I’m in. Thank you isn’t enough.', 'Peter Aleman'],
    ['Laura is a certified StoryBrand guide who knows how to craft a winning message to customers/clients. As a business owner, I am constantly bombarded by marketing opportunities, and I’ve had some hits and misses. But the best decision I ever made was consulting with Laura. She completely transformed the way I talk about my business and communicate with potential clients. My only regret is waiting so long to enlist her expertise! I highly recommend her!', 'Josh Massingill, Esq.'],
    ['Hire Laura!!! You\'ll be sorry if you pass her up and go with someone else. Laura was a master at getting the right brand messaging out of us. Other consultants like to come up with their ideas for what you could be doing. Laura was spot on in helping us properly describe and explain who we already are and what we are already providing. Very satisfied.', 'Jeffrey Palermo'],
    ['Laura is a fantastic listener and heard my problem: how will we get into the future from where we are now? Laura gave me a plan to understand and reach our ideal clients that was fresh and true to my business principles and goals. Because of Laura, we now have a clear understanding of our ideal client and a new way to relate to her. Our future is now enjoyable and bright. The picture is sharp and clear. I can\'t say enough how much I appreciate Laura\'s talent and expertise. Her work is just priceless.', 'Eloisa Alvarez'],
    ['Working with Laura is a dream - not only is she a marketing whiz, she holds herself to the highest standards and deeply cares about delivering a superior experience for her clients. It\'s a sheer pleasure working with such a professional, fun, and energetic high achiever.', 'Glen Sanford'],
    ['There aren\'t a lot of people in business who bring a combination of sterling professionalism, knowledge, experience and an infectious attitude to the table…Laura is one of those few. Laura\'s educational pedigree combined with her years of experience and wide-ranging skill-set make her an essential part of any team, she always strives to stay right on the cutting edge but has a sixth sense for distinguishing result-driven opportunities from passing fads. Working with Laura has been a consummate pleasure.', 'Alex Avedikian'],
    ['Laura is personable and a joy to work with. She really helped hone our message and take what we started at the StoryBrand workshop and bring it home. I look forward to working even further with Laura to help us really put our StoryBrand to work.', 'Michael Wilk'],
    ['Laura is an endless book of opportunities and ideas to grow your company. She leads horses to water. She is a marketing connoisseur who unselfishly shares her knowledge. She is a business consultant by nature who drops gems in casual conversations. She is someone who cares about her community, her family, her friends, your business, and you.', 'Jessica Lovett'],
    ['Laura is great to work with, super friendly, knowledgeable, with lots of attention to detail and is just a beautiful individual inside and out!', 'Dr. Elizabeth Lowery'],
    ['Laura has taken the time and effort to not only help us find the best marketing plan to most efficiently meet our client base but also introduce us to NUMEROUS helpful people to help our business grow. Her sincerity and love of her community are undeniable, we thoroughly enjoy working with her.', 'Don Denham'],
    ['Laura, I want to thank you for the constructive enlightened energy you bring to this journey. You have spent a lifetime developing your talent, wisdom, and soul — and this project is one of the lucky recipients. I am profoundly grateful for you. It\'s been a great experience working with you, and I look forward to everything we will continue to create.', 'Christina Trevino'],
    ['I have never experienced such a high volume sales day — ever! We crushed the competition! I think you hit a grand slam with the advertising! Thank you very much for all the work and dedication you put into this sale. The success is due to your brains!', 'Jennifer Soto'],
    ['I wanted to take this opportunity to tell you how much I love the new website! It\'s a great sales tool! After I make a call, I refer my customer or prospect to the site, knowing the information they get there will give me credibility and make my job easier. Excellent work!', 'Jerrianne Johns'],
    ['Laura, it has been a wonderful experience working with you for the past 5 years. When we first met, I was immediately impressed with your professionalism, level of marketing knowledge, and openness to ideas and developing a win/win partnership. Over the years, I have come to regard you as one of my most savvy clients. You are on top of everything and carefully consider every aspect in order to make the best marketing decision for your client. You have been a wonderful partner!', 'Dianne Shelton'],
    ['I cannot say enough great things about Laura Terry and her team. Partnering with them has helped launch our business on the right foot. They helped us plan a soft opening event that has given us incredible traction within the community and helped forge our presence online. Laura Terry has been an incredible partner and we appreciate her ability to effectively market our brand to this tight knit community.', 'Rob Aloe'],
    ['I can\'t even begin to tell you how impressed I am with our new website! It is so informative and easy to go through! I wanted to let you know that it is unbelievably evident on the amount of time and energy that was put into it! Thank you so much — I will be sure to let everyone know about it!', 'Jay Fitzmaurice'],
    ['We loved working with Laura on a publicity strategy for a multi-market fitness retailer. She demonstrates such depth and breadth of marketing experience from social media to events and moves the pieces of her plan into place with enthusiasm and creativity. She understands how to balance demand generation marketing and brand awareness with communication that builds relationships and elevates reputations.', 'Laura Bond Williams'],
    ['Laura has an incredible insight into design and marketing messages. Where most marketers would be colorblind, Laura is able to see the correlation between color, layout, and message. She has been wonderful to work for and with, as we have had both dynamics in the past six years. I\'ve learned that where most marketers would stop and say they are satisfied with their output, she is able to take it to a whole new polished level. I highly recommend her if you are looking to rebrand your marketing message. She understands that value is in the customer\'s journey and that we are here to be their guide in facilitating the best outcome for them.', 'April Aguren'],
    ['Laura in my opinion is an incredible Marketing strategist. On our first call she immediately identified specific areas where our website should be optimized for keyword searches. There were several incredible tips she offered, blind spots I didn’t see, that she clearly pointed out. I have actionable steps now that I’ll be implementing for our 2022 Marketing strategy. I highly recommend Laura for her experience and genius mind!', 'Rick Ortiz'],
    ['Laura is both a breath of fresh air and a force to be reckoned with. A naturally effective and compassionate team leader, she\'s not afraid to challenge the bounds, constantly pushing herself and her team to be better, think differently, bring creativity, and push efficacy in all they do.Laura has an eye for design/aesthetics and a knack for helping businesses tell their story via marketing. With years of marketing/branding expertise behind her, she never settles for anything less than the best and she treats ALL her clients like her #1 client to whom she makes herself FULLY available. She\'s tremendously sincere and easy to get ahold of any time you need anything. On a personal and professional level, she\'s definitely someone to have in your network. Laura, always a pleasure working with you. Thank you for all you do!', 'Anna Price'],
    ['Laura is a hardworking and dedicated individual who truly cares about the communities she works with. She is committed to working with you to understand your values and really capture what it means to be a part of your community. The quality she provides is second to none with professional designers and state-of-the-art printing equipment at her fingertips to create magazines that are both sleek and eye catching. I highly recommend Laura Terry of N2 if you wish to showcase members of your community. Laura offers a great service that produces high-quality publications of residents and local businesses, giving them the exposure they deserve.', 'Treigh Hubbard'],
    ['Laura is one of the most passionate and caring marketers that I know. Her years of experience in the Corporate World prepared her to take those skills to the small business community. She is innovative and an excellent community builder.When I was looking to access some of the highest income neighborhoods in our area, I engaged Laura The Neighborhood Ninja to get me on the coffee tables instead of the trashcans. If you are looking for a great marketing partner to help you grow your business, Laura should be your first call.', 'Jeff Kikel'],
    ['In starting new ventures it is important to have people in your corner. Laura is one of those people for me. Laura became a client and an advocate for helping me grow the Shine Brand in our community. Laura is incredibly detailed and shared her expertise in advertising with the N2 brand and in connecting with others who might need our services. Thank you Laura!', 'Chris Fisher'],
    ['In my 25 years of business in a variety of fields, I have had the privilege of working with many outstanding individuals. In that time, I have never worked with a more inspiring and capable catalyst for positive change than Laura Capes Terry. Laura is an inspiring visionary who creates a picture of what can be. However, most stop there. She does not. Laura then proceeds to go forth and make that vision happen, despite whatever obstacles and challenges she may encounter along that path. I have personally watched as Laura overcame the odds and made the seemingly impossible happen. Laura put all of her heart and soul as well as personal resources into creating Avery Ranch Living. The community of Avery Ranch and its residents have a true gift in Laura and a loyal ambassador for the good of the community. I would wholeheartedly recommend her in any endeavor and stand along side her on any battlefield.', 'Kirk Miller'],
    ['Laura\'s professionalism and energy is without equal, and it was a pleasure doing business with her as a sponsor / advertiser in Avery Ranch Living magazine at N2. Her personal attention to detail for my advertising needs goes well beyond that which I would have expected after the initial sale. She dedicates significant time and effort to ensure my advertising efforts (and dollars) are maximized each month. I highly recommend Laura and N2.', 'Mike Shenk'],
    ['The residents of Avery Ranch are fortunate to have Laura working tirelessly for their community! As a resident herself, Laura truly cares about the people who live there and her passion and compassion shows in all elements of her work. As a colleague, mentor and friend, I can personally attest to Laura\'s dedication to excellence!', 'Rachelle Grossman'],
    ['I absolutely enjoy working with Laura as my publisher. Not only did she work tirelessly on publishing the new Avery Ranch Living magazine, Laura did it while being true to her business philosophy of being of value to her relationships. Laura is an excellent networker and an even better businesswoman with sound ideas and organization skills. I\'m glad to call her a colleague and a friend whom I choose to do business with!', 'Michelle Allen'],
    ['Laura is an extremely passionate woman, particularly when it comes to her community. Her work as the publisher of Avery Ranch Living bears that out. She is also very organized, detailed, and energetic. I am lucky to know she is both my colleague and friend. I would recommend anyone interested in doing business in the Avery Ranch community to seek Laura out and work with her. You will find her extensive background in Marketing and Advertising to be invaluable for your business.', 'Gabriel Cepeda'],
    ['Laura launched and published a new community magazine in a short time without sacrificing quality. She delivered as promised and fulfilled the needs of the community and focus groups as demonstrated by a string of strong testimonials and feedback from the readers and residents. Laura is a true professional and excels at networking, partnering, and creating powerful connections to get things done. She is always moving forward and creatively finds solutions to keep a project on task. From a networking perspective she is a social hub of valuable connections. Most important to our non-profit organization, Laura went above and beyond to help our mission and \'shouted from the rooftops\' to get the word out about Texas Humane Heroes. Her efforts created success for both our organization and for her publication, proving that social cause marketing works and is effective for companies, as well as the social-cause that is being advocated. Laura proved this while helping to save more animals. We are grateful for her work, efforts, passion, and professionalism.', 'Ron Marullo'],
    ['Laura is a true gift!! And a go-getter on our team. Her persistence to get the job done and publishing her magazine in the community has all of us praising her. She is always managing to bring visitors to the group and has many connections in the north Austin area. I highly recommend Laura to anyone who is looking for business advertising and effectiveness.', 'Judy Matejczyk'],
    ['I’ve had an outstanding experience working with Laura in a B2B partnership setting. She is really a cut above the rest when it comes to knowing her industry, trends, products, demographics and buyer behavior. She is a great communicator (in writing and in conversation) and is ultra-timely in all that she does. I appreciate her ability to tackle any big change in stride and keep all internal and external stakeholders focused on the same goal. I can count on Laura for in-depth questions, thinking outside the box and incorporating encouragement and compliments when getting tough tasks and responsibilities completed.', 'Warren Westcott'],
    ['Thank you for being such a positive influence for me over the years. Both understanding the fiscal limitations regarding the market and finding more creative ways to grow our brand in the market. The Omaha Market has been challenging for us to say the least. While I am very proud of the advances we have made; I owe a great deal to you and your guidance. Best of luck to you in your pursuits.', 'James Keyes'],
    ['Laura is a true leader in the marketing component of the specialty fitness industry. I have had the pleasure of working with her on the evolution of our marketing strategies to directly and indirectly grow our commercial sales presence in the Midwest. She leads through a team input approach and has the industry experience to lead/guide us into newer areas of marketing including capitalizing on the the digital marketing medium that has really helped our exposure as a company.', 'Chad Witt'],
    ['Laura has the ability to develop a brand, create an image for that brand, and establish a market dominant position. Each time Laura presented our locations with a marketing approach we were nearly guaranteed to set record sales figures. It was her knowledge of not only the region she was located in, but the market as a whole spanning 4 states that gave us the edge over the competition. Laura is ethical, honest, established and proven both professionally and personally and I am privileged to call her a friend.', 'John Trigg'],
    ['When it comes to marketing, Laura Capes Terry, aka the MAVEN, is a rare breed. She is simply amazing. It goes without saying that Laura Capes Terry would have an immediate and positive impact on any business. Laura\'s innovative ideas and approach to business, marketing, social media and search engines on the Internet are legendary. I don\'t know if I\'ve met anyone in business with better marketing, communication, and organizational skills and such a pleasure to work with. Her people skills, creativity, intuitive leadership, and enthusiasm are unmatched in the industry along with her genuine interest in Client Value. I have met few people with such passion for their work or life itself. If you\'re looking for someone to help you build long-term relationships with your clients while boosting your company\'s profits, Laura is your woman. She is definitely a class act both personally and professionally. This is the reason why I am proud to call Laura my friend.', 'Roger Simpson'],
    ['Laura is a top-of-the-line business and marketing consultant who continually pushes her limits in her own areas of personal and professional development. Her passion and drive to represent the highest level of expertise in her emerging field of interactive marketing and social media is truly awe inspiring! I value her integrity, work ethic, and consider her a trusted partner and invaluable resource.', 'Grant Moyer'],
    ['Laura and her team are absolutely incredible! They listen to their clients needs and help them come up with a great plan that will benefit and compliments their clients’ business.', 'Michele J-Webb'],
    ['If you\'re looking for a powerful team to help you define or tell your story, or your company\'s story, look no further. Laura and Terry have the skills and expertise you are looking for. Every step of the process has been amazing, and they made me feel like we did it as a team. I transitioned out of full time employment to start my own business 6 years ago, and although I\'ve been very successful, I now have a personal brand, defined by those I\'ve helped, and a story to tell every potential client!', 'Tim Novak'],
    ['Laura and her team are truly experts in their craft. I can’t recommend the Grayson Media & Marketing team enough for any business looking for an expert marketer! We are VERY happy customers.', 'Tori Clark'],
    ['Laura has been wonderful to work with as our local marketing consultant. We opened a new business in August and were having problems getting more customers and brand recognition. She helped us develop a digital, print and social media strategy that works with our franchisor marketing rules. She understands Williamson County very well and we are executing the strategy and building our business. Thank you Laura.', 'Russ Burleson'],
    ['I can\'t say enough about Laura!! She has been absolutely amazing, and her dedication is unmatched! I love being able to trust someone completely enough to not worry. Your business will be in fantastic hands!', 'Rebecca Lockerbie'],
  ];

  function ReviewsPage() {
    const { BookButton } = window;
    return (
      <div>
        {/* Hero */}
        <section className="bg-tint section--sm">
          <window.Container>
            <div className="reveal" style={{ maxWidth: 760, margin: '0 auto', textAlign: 'center', paddingTop: 24, paddingBottom: 24 }}>
              <Pill variant="soft" style={{ marginBottom: 16 }}>Reviews</Pill>
              <h1 className="h-display" style={{ fontSize: 'var(--fs-h1)', marginBottom: 14 }}>What clients say about working with Laura</h1>
              <p className="lead">Clients consistently describe Laura as a trusted guide, strategic thinker, and creative partner who brings both heart and clarity to their marketing.</p>
            </div>
          </window.Container>
        </section>

        {/* Featured */}
        <section className="bg-page section">
          <window.Container>
            <div className="grid grid-3">
              {FEATURED.map(([q, who, org], i) => (
                <div key={i} className="reveal card" style={{ display: 'flex', flexDirection: 'column' }}>
                  <div style={{ color: 'var(--color-accent)', marginBottom: 12 }}>
                    {[0, 1, 2, 3, 4].map((s) => <i key={s} className="fa-solid fa-star" style={{ fontSize: 14, marginRight: 3 }}></i>)}
                  </div>
                  <p style={{ fontFamily: 'var(--font-body)', fontSize: 15.5, lineHeight: 1.7, color: 'var(--text-body)', fontStyle: 'italic', margin: '0 0 16px', flex: 1 }}>{q}</p>
                  <p style={{ fontFamily: 'var(--font-body)', fontSize: 14, fontWeight: 700, color: 'var(--text-heading)', margin: 0 }}>{who}</p>
                  <p style={{ fontFamily: 'var(--font-body)', fontSize: 13, color: 'var(--text-muted)', margin: '2px 0 0' }}>{org}</p>
                </div>
              ))}
            </div>
          </window.Container>
        </section>

        {/* Wall */}
        <section className="bg-card section">
          <window.Container>
            <window.SectionTitle title="In their own words"
              sub="A few more of the many kind words from business owners and leaders Laura has guided over the years." />
            <div className="heart-divider" aria-hidden="true"><i className="fa-solid fa-heart"></i></div>
            <div style={{ marginTop: 44, columns: '3 280px', columnGap: 24 }}>
              {WALL.map(([q, who], i) => (
                <div key={i} className="reveal" style={{ breakInside: 'avoid', marginBottom: 24, background: 'var(--surface-tint)', borderRadius: 'var(--radius-lg)', padding: '24px 26px' }}>
                  <i className="fa-solid fa-quote-right" style={{ color: 'var(--color-accent)', fontSize: 20, marginBottom: 12, display: 'block' }}></i>
                  <p style={{ fontFamily: 'var(--font-body)', fontSize: 15, lineHeight: 1.65, fontStyle: 'italic', color: 'var(--text-body)', margin: '0 0 14px' }}>{q}</p>
                  <p style={{ fontFamily: 'var(--font-body)', fontSize: 13.5, fontWeight: 700, color: 'var(--text-heading)', margin: '0 0 4px' }}>{who}</p>
                  <p style={{ fontFamily: 'var(--font-body)', fontSize: 11.5, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--color-primary)', margin: 0 }}>
                    <i className="fa-solid fa-circle-check" style={{ marginRight: 6 }}></i>Verified client review
                  </p>
                </div>
              ))}
            </div>
          </window.Container>
        </section>

        {/* CTA */}
        <section className="bg-dark section">
          <window.Container>
            <div className="reveal" style={{ textAlign: 'center', maxWidth: 620, margin: '0 auto' }}>
              <h2 className="h-display" style={{ fontSize: 'var(--fs-h2)', color: '#fff', marginBottom: 14 }}>Ready to be the next success story?</h2>
              <p style={{ fontFamily: 'var(--font-body)', fontSize: 'var(--fs-lead)', lineHeight: 1.6, color: 'rgba(255,255,255,0.92)', margin: '0 0 28px' }}>
                Start with a short, no-pressure conversation about where the business is and where it wants to go.
              </p>
              <BookButton size="large" variant="accent" style={{ background: '#fff' }}>Work With Laura <i className="fa-solid fa-heart"></i></BookButton>
            </div>
          </window.Container>
        </section>
      </div>
    );
  }
  window.__pages = window.__pages || {};
  window.__pages.reviews = ReviewsPage;
})();
